
version: "3"

services:
  app:
    build: .
    container_name: app
    ports:
      - 3333:3333
    environment:
      - MONGO_URL=mongodb://db_mongo
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    tty: true
      
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata: 
